### ISSUE TITLE
Deprecate exclude_enum

### ISSUE THREAD

**Issue by greyblake** [albertosaurus/power_enum#15]
I think it would be reasonable to deprecate `exclude_<enum>` scope methods in favor of  `without_<enum>` method to make syntax compatible with state machine, since both provide `with_*` scopes.

**Comment by albertosaurus** [comment]
Not every PowerEnum user uses state machines...

**Comment by greyblake** [comment]
But we do)

**Comment by albertosaurus** [comment]
Then shouldn't we do this via local aliases?

**Comment by greyblake** [comment]
Already done. The was case when I needed to delegate methods. I though it would be better to have `without_` than `exclude_` methods. At least I was looking for `without_` firstly.

**Comment by albertosaurus** [comment]
Maybe I'll do this for version 2.
