### ISSUE TITLE
Allow to install gem from github (signing key issue).

### ISSUE THREAD

**Issue by greyblake** [albertosaurus/power_enum#21]
Since you're the one, who can has signing key, it's not possible to insall the gem from Github for others because of lack pf private key:

```
Errno::ENOENT: No such file or directory - gem-private_key.pem
An error occurred while installing power_enum (1.3.1), and Bundler cannot continue.
Make sure that `gem install power_enum -v '1.3.1'` succeeds before bundling.
```

As far as I understand the key is necessary only when you build the gem.
So could you add a codition to gemspec, like this: https://github.com/delano/rye/pull/30/files#L2R71
To allow people use the gem from github/forks without removing `singing_key` manually.

**Comment by albertosaurus** [comment]
The problem is that I'm using Jeweler to generate the gemspec.  I'm thinking this may be reason enough to dump it, but it's something I need to think through.

**Comment by albertosaurus** [comment]
I'm making the signing key conditional in version 1.3.3. I guess i can just manually tweak the gemfile until I migrate off of Jeweler.
