### ISSUE TITLE
Associations of powe enum models with other models not working in Rails 4

### ISSUE THREAD

**Issue by rashilastayntouch** [albertosaurus/power_enum#27]
In power_enum module EnumClassMethods, the 'all' method is overridden as,

`def all
  return @all if @all
  @all = load_all.collect{|val| val.freeze}.freeze
end
`
([Link to the method in power_enum repository]( https://github.com/albertosaurus/power_enum/blob/b79a2561112946d53f44b569617909a350bb8d27/lib/power_enum/enumerated.rb#L145))

As Rails 4 has modified its target_scope method in 'lib/active_record/associations/association.rb' ([Link to the method in rails repository](https://github.com/rails/rails/blob/e9d6b85f3e834ceea2aeabe4cbaa96a7c73eb896/activerecord/lib/active_record/associations/association.rb#L123,)) when we define any association of any Rails model with a power_enum model, the association throws an error.

Eg;

# power_enum model
class BookingStatus < ActiveRecord::Base
  acts_as_enumerated
  has_and_belongs_to_many :bookings
end

# Normal model
class Booking < ActiveRecord::Base
	has_and_belongs_to_many :booking_statuses
end

> b = Booking.first
>b.booking_statuses
>ArgumentError: [] is not an ActiveRecord::Relation

**Comment by albertosaurus** [comment]
a) This code is old, unmaintained, and only preserved for posterity. The readme explicitly says for Rails 4 and later look into https://github.com/albertosaurus/power_enum_2.

b) Far more important. If you're defining any kind of a `has...` relationship on a model that `acts_as_enumerated` it's a near certainty you're making a gross conceptual error. Please read the readme in full.
