### ISSUE TITLE
Rename to power_enum

### ISSUE THREAD

**Issue by greyblake** [albertosaurus/power_enum#9]
Why don't you rename the repo to `power_enum`?
It would be less confusing... And Google would show better search results for `power_enum` query.

**Comment by albertosaurus** [comment]
Legit.  I will, hopefully this weekend.

**Comment by albertosaurus** [comment]
Done.

**Comment by greyblake** [comment]
Forgot to change link to source code in gemspec: http://rubygems.org/gems/power_enum

**Comment by albertosaurus** [comment]
Right.  Will fix.
